ci: revert to workflow_dispatch and enable corepack and pnpm
Now publish workflow is using workflow dispatch action again and corepack/pnpm is enabled.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,9 +1,7 @@
 name: Publish to NPM Registry
 
 on:
-  push:
-    tags:
-      - "v*"
+  workflow_dispatch:
 
 jobs:
   publish:
@@ -14,6 +12,11 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
+
+      - name: Enable Corepack & setup pnpm v10.20.0
+        run: |
+          corepack enable
+          corepack prepare pnpm@10.20.0 --activate
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -30,12 +33,17 @@ jobs:
       - name: Build project
         run: pnpm build
 
-      - name: Bump version in package.json from tag
+      - name: Detect tag and bump version in package.json
         run: |
-          TAG_VERSION=${GITHUB_REF##*/}
-          NEW_VERSION=${TAG_VERSION#v}
-          jq --arg version "$NEW_VERSION" '.version = $version' package.json > package.tmp.json
-          mv package.tmp.json package.json
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_VERSION="${GITHUB_REF##*/}"
+            NEW_VERSION="${TAG_VERSION#v}"
+            jq --arg version "$NEW_VERSION" '.version = $version' package.json > package.tmp.json
+            mv package.tmp.json package.json
+          else
+            echo "::error::Este workflow só pode ser disparado por uma tag!"
+            exit 1
+          fi
 
       - name: Publish to NPM
         run: npm publish --access public
